version: "3.9"

services:
  project:
    container_name: application
    build:
      context: ./project
    restart: always
    volumes:
      - static:/static
    env_file:
      - .env
    ports:
      - 8000:8000

  nginx:
    container_name: webserver
    build:
      context: ./nginx
    restart: always
    depends_on:
      - project
    ports:
      - 443:443
    volumes:
      - static:/static

volumes:
  static: