version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - static:/static
    ports:
      - 8000:8000
    image: chikwebsite
    container_name: app
  
  nginx:
    build: ./nginx
    image: nginx:latest
    ports:
      - 8080:80
    container_name: webserver
    restart: always
    volumes:
      - static:/static
    depends_on:
      - app

volumes:
  static: